### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by MusicallyInspired** [PSebs/SonicCD-SteamPlay#1]
I was overjoyed to find this. However, after following the instructions and launching the game nothing happens. It exits as soon as it launches. Is there something I'm missing?

**Comment by PSebs** [comment]
Oh yeah. Now that I actually got a steam deck. It crashed because of a glib error. I need to check to get around it.

**Comment by PSebs** [comment]
Yeah uh, a bit late but it should be resolved now. It now uses an appimage to run off of.

**Comment by MusicallyInspired** [comment]
I'm afraid it still doesn't do anything. Immediately after pressing play and selecting "Launch Game" it just exits. Same behaviour. I quit Steam, deleted the folder, restarted Steam, quit Steam, added the new folder from the releases, restarted Steam, still doesn't work. I quit Steam again, deleted the folder, restarted Steam, quit Steam, downloaded the code repository instead of the releases archive, extracted that, restarted Steam, retried SonicCD-Decomp in Compatibility, still doesn't work. :\

**Comment by PSebs** [comment]
Is regta_wrapper or the appimage marked as an executable? That's how I hoped it was made it sure to work when I put it in the tar archive in the current release. That was the underlying issue for me. You could try to right click the file and check or use chmod +x on it.

**Comment by MusicallyInspired** [comment]
That was it. "regta_wrapper" was not marked as executable. Checking that box made it work at last!
